stages:
  - validate
  - plan
  - approve
  - apply
  - deploy
  - cleanup

# Global variables
variables:
  AWS_REGION: "eu-central-1"
  TF_IN_AUTOMATION: "true"
  # Optional: If storing Terraform state in S3, you might have:
  # TF_BACKEND_CONFIG: "-backend-config=bucket=my-terraform-state-bucket -backend-config=region=eu-central-1"

cache:
  key: terraform
  paths:
    - .terraform/

##################################
# 1) Validate Terraform
##################################
terraform-validate:
  stage: validate
  image: hashicorp/terraform:latest
  script:
    - terraform init -backend=false
    - terraform validate
  only:
    - merge_requests
    - main

##################################
# 2) Terraform - Plan
##################################
terraform-plan:
  stage: plan
  image: hashicorp/terraform:latest
  script:
    - terraform init
    # If you have a remote backend, run something like:
    # terraform init $TF_BACKEND_CONFIG
    - terraform plan -var-file=terraform.tfvars -out=tfplan
  artifacts:
    paths:
      - tfplan
    when: always
  only:
    - merge_requests
    - main

##################################
# 3) Manual Approval Before Apply
##################################
terraform-approve:
  stage: approve
  image: alpine:latest
  script:
    - echo "Waiting for manual approval to apply Terraform changes..."
  when: manual
  allow_failure: false
  only:
    - merge_requests
    - main

##################################
# 4) Terraform - Apply
##################################
terraform-apply:
  stage: apply
  image: hashicorp/terraform:latest
  dependencies:
    - terraform-plan
  needs:
    - terraform-approve  # Enforce that the manual approval must happen first
  script:
    - terraform init
    # If you have a remote backend, run something like:
    # terraform init $TF_BACKEND_CONFIG
    - terraform apply -auto-approve tfplan
  only:
    - main

##################################
# 5) Deploy Kubernetes Workloads to EKS
##################################
deploy-k8s:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f k8s/
  environment:
    name: production
    kubernetes:
      agent: eks-gitlab-agent
  only:
    - main

##################################
# 6) Deploy ECS Tasks via Ansible
##################################
deploy-ecs:
  stage: deploy
  image: ansible/ansible:latest
  script:
    # Configure AWS credentials with environment variables
    - ansible-playbook ansible/ecs-deploy.yaml
  only:
    - main

##################################
# Rollback Mechanism (On Failure)
##################################
rollback:
  stage: cleanup
  when: on_failure
  image: hashicorp/terraform:latest
  script:
    # 1) Destroy Terraform-managed infrastructure
    - terraform init
    - terraform destroy -auto-approve
    # 2) Remove K8s resources
    - kubectl delete -f k8s/ || true
    # 3) Roll back ECS tasks
    - ansible-playbook ansible/ecs-deploy.yaml --extra-vars "rollback=true"
  # This only triggers if the pipeline fails in an earlier stage
  only:
    - main
