workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "testing"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

stages:
  - validate
  - plan
  - approve
  - apply
  - deploy
  - cleanup

# Global variables
variables:
  AWS_REGION: "eu-central-1"
  EKS_CLUSTER_NAME: "my-eks-cluster"
  TF_IN_AUTOMATION: "true"

cache:
  key: terraform
  paths:
    - .terraform/

##################################
# 1) Validate Terraform
##################################
terraform-validate:
  stage: validate
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  script:
    - terraform init -backend=false
    - terraform validate

##################################
# 2) Terraform Plan
##################################
terraform-plan:
  stage: plan
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  script:
    - cd terraform
    - terraform init
    - terraform plan -var-file=terraform.tfvars -out=tfplan
  artifacts:
    paths:
      - terraform/tfplan
    when: always

##################################
# 3) Terraform Apply
##################################
terraform-apply:
  stage: apply
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  needs:
    - job: terraform-plan
      artifacts: true
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve tfplan

##################################
# 4) Deploy Kubernetes Workloads to EKS
##################################
deploy-k8s:
  stage: deploy
  image: ubuntu:20.04
  needs: ["terraform-apply"]
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -y && apt-get install -y curl unzip
    # Install AWS CLI v2
    - curl -Lo awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    - unzip awscliv2.zip && ./aws/install
    # Install kubectl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl && mv kubectl /usr/local/bin/
    # Generate kubeconfig
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
    - kubectl apply -f k8s/
  environment:
    name: production
    kubernetes:
      agent: eks-gitlab-agent

##################################
# 5) Deploy ECS Tasks via Ansible (Run on AWS)
##################################
deploy-ecs:
  stage: deploy
  image: willhallonline/ansible:alpine
  needs: ["terraform-apply"]
  script:
    - apk update && apk add --no-cache python3 py3-pip openssh-client curl unzip
    # Install Terraform
    - curl -LO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    - unzip terraform_1.5.7_linux_amd64.zip -d /usr/local/bin/
    # Install AWS CLI v2 (required for EKS kubeconfig)
    - curl -Lo awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    - unzip awscliv2.zip && ./aws/install
    # Use Terraform outputs
    - export AWS_DEFAULT_REGION=$AWS_REGION
    - cd terraform  # Navigate to Terraform directory
    - ansible-playbook -i "localhost," -c local ../ansible/ecs-deploy.yaml
      --extra-vars "subnet_ids='$(terraform output -raw private_subnet_ids)'
                    security_group_ids='$(terraform output -raw ecs_security_group_id)'
                    task_definition='$(terraform output -raw ecs_task_definition)'
                    ecs_cluster_name='$(terraform output -raw ecs_cluster_name)'"

##################################
# 6) Rollback Mechanism (On Failure)
##################################
rollback:
  stage: cleanup
  when: on_failure
  image: hashicorp/terraform:latest
  script:
    - terraform init
    - terraform destroy -auto-approve
    - apk update && apk add --no-cache curl python3 py3-pip
    - pip3 install ansible awscli
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl && mv kubectl /usr/local/bin/
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -y && apt-get install -y awscli
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
    - export KUBECONFIG=$HOME/.kube/config
    - sed -i 's/v1alpha1/v1beta1/g' $KUBECONFIG
    - kubectl delete -f k8s/ || true
    - ansible-playbook -i "localhost," -c local ansible/ecs-deploy.yaml --extra-vars "rollback=true"
