apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace: default
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fargate-app-config
  namespace: fargate
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
