apiVersion: v1
kind: ServiceAccount
metadata:
  name: fargate-app-sa
  namespace: fargate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fargate
  name: fargate-app-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fargate-app-binding
  namespace: fargate
subjects:
  - kind: ServiceAccount
    name: fargate-app-sa
    namespace: fargate
roleRef:
  kind: Role
  name: fargate-app-role
  apiGroup: rbac.authorization.k8s.io
