apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=  # base64-encoded "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: fargate-app-secret
  namespace: fargate
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=  # base64-encoded "password"
